name = "gondolin-blueprint"
defaultTargets = ["GondolinBlueprint", "blueprint-gen"]

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso"
rev = "v4.29.0"

[[require]]
name = "VersoBlueprint"
git = "https://github.com/leanprover/verso-blueprint"
rev = "v4.29.0"

[[require]]
name = "Gondolin"
path = ".."

[[lean_lib]]
name = "GondolinBlueprint"

[[lean_exe]]
name = "blueprint-gen"
root = "GondolinBlueprintMain"
